### ISSUE TITLE
Weather icon and info not showing?

### ISSUE THREAD

**Issue by greed-d** [jorgedasilva91/KWGT-At-A-Glance-Widget#2]
Current Device: POCO F3

OS : LineageOS 20

I've followed everything and even done troubleshooting from here 

https://telegra.ph/KWGT-At-A-Glance-Instructions-04-28

but still weather info and icon are not displayed 

![Screenshot_20231030-123458_Trebuchet](https://github.com/jorgedasilva91/KWGT-At-A-Glance-Widget/assets/58597122/584bfe05-d9cc-4a9e-be21-8bd435e7ff36)

this is what it looks like inside KWGT

![Screenshot_20231030-123445_Kustom Widget](https://github.com/jorgedasilva91/KWGT-At-A-Glance-Widget/assets/58597122/4b236353-a699-4b61-91e0-d6092ecbc3d4)

also even though I selected `condition` it still displayed AQ

**Comment by greed-d** [comment]
Ohh there's a support group

**Comment by mwhd96** [comment]
I also experienced the same
How do you fix that?
Also where can I join the support group?

**Comment by greed-d** [comment]
> I also experienced the same How do you fix that? 

I didn't...
I started using a new app called Smartspacer, it gives pretty neat and handy widgets
